language: node_js
node_js:
    - "6.3.1"
env:
    - CXX=g++-4.8
addons:
    apt:
        source:
            - ubuntu-toolchain-r-test
        packages:
            g++-4.8
services:
    - mongodb
after_success:
    - npm run coveralls
branches:
    only:
        - master
